### ISSUE TITLE
WBCE 1.2 alpha4: multiple Issues with modules

### ISSUE THREAD

**Issue by instantflorian** [WBCE/WebsiteBaker_CommunityEdition#134] opened 2016-05-17 08:39 UTC
Topics:
when calling a topics detail page in FE, instead of the page just an error occurs:
Fatal error: Call to a member function page_link() on a non-object in /.../framework/functions.php on line 596

Bakery:
Unable to create items
 Fatal error: Cannot redeclare rm_full_dir() (previously declared in /.../framework/functions.php:27) in /.../framework/functions.php on line 64

Classic News:
same as Bakery, unable to create groups or news items

ProCalendar:
No frontend output, just an error
Fatal error: Call to a member function is_authenticated() on a non-object in /.../modules/procalendar/functions.php on line 577

MultiPageSettings:
No BE interface, just an error
 Fatal error: Call to a member function set_var() on a non-object in /.../modules/MultiPageSettings/tool.php on line 96

**Comment by instantflorian** [comment] 2016-05-17 08:47
Notice: I made an WBCE issue for this, because all mentioned errors do not show up with WBCE 1.1.6

**Comment by NorHei** [comment] 2016-05-18 05:28
hast Du eventuell eine Testinstallation wo ich mir das direkt anschauen kann ?

**Comment by NorHei** [comment] 2016-05-19 04:57
As i thought bakery is a simple Bakery problem . 

save_item.php on line   34  and 37 

replace require whith require_once . 

Optinal you can simply remove line 34, but then the module won't run on WB Classic 

Maybe we should talk to the bakery Author if he fixes this as it would lead to trouble whith WB classic too sooner or later , optionally we can open a Bakery branch for WBCE , but that second best .

**Comment by NorHei** [comment] 2016-05-19 05:01
Cant reproduce news issue anymore ?  You installed the new fixed module ?

**Comment by NorHei** [comment] 2016-05-19 05:24
About   MultiPageSettings:

Fixed tool.php is on test installation . 

The origin of the problem was the heavy use of global vars instead of function parameters. 
This was one of the reasons why DV feared to modify loading of modules and tools , as several modules do a heavy abuse of Global vars  and this leads to problems when changing the enviroment  of the script (moving it to a function, class or namespace)

The fix should be Classic compatible so again we can ask the Author if he accept the fix. Or make our own branch.   


Can you please check if i forgot some things , otherwise this should be it .

**Comment by NorHei** [comment] 2016-05-19 05:26
btw, thanks for all the testing

**Comment by NorHei** [comment] 2016-06-03 04:29
Can i close this now ?

**Closed** 2016-06-03 05:30 UTC
Labels: bug, help wanted

**Comment by NorHei** [comment] 2016-06-08 08:35
http://www.jqueryscript.net/form/jQuery-Plugin-To-Save-Restore-Form-Data-formsaver-js.html

Schaut interessant aus , was denkst Du ?



Am 03.06.2016 um 07:30 schrieb instantflorian:
> Closed #134
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/134>.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/WBCE/WebsiteBaker_CommunityEdition/issues/134#event-680716819>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB0fq7rn84saGUprbmE_atkqlU0Z5czhks5qH7wHgaJpZM4IgDOg>.
>

-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792

**Comment by NorHei** [comment] 2016-06-08 08:37
http://shaneriley.com/jquery/remember_state/


-- 
Norbert Heimsath
Mergelstraße 25
45478 Mülheim an der Ruhr
Tel: 0208 55792
