### ISSUE TITLE
Unable to create new groups in backend

### ISSUE THREAD

**Issue by cwsoft** [WBCE/WebsiteBaker_CommunityEdition#35] opened 2015-08-25 07:56 UTC
Seems commits 6b309fedf3 respective 672a8a8c5fadc introduced some regression preventing to create new user groups via the WBCE backend. Tested on Windows 7 with PHP 5.6.11 and MySQL 5.6.25. Can this be confirmed by others?

**Comment by instantflorian** [comment] 2015-08-25 08:21
Can partly confirm. The groups _are_ created and can be selected at the useraccount management area, but the groups do not show up in groups list unless there is a user assigned to them.

**Comment by SgtNops** [comment] 2015-08-25 11:15
this sounds like a good trace.

**Comment by SgtNops** [comment] 2015-08-25 11:18
hmmm, can not confirm right now... Updating installation

**Comment by NorHei** [comment] 2015-08-25 11:36
Ok, Confirmed. Please assign this to Marmot as the changes in the DB query are the reason for this. The old ones whith subqueries did not have the issues. Replacing this whith the old ones solves the Problem, but maybe he got a better idea to fix this .

**Comment by marmotwb** [comment] 2015-08-27 20:25
Fixed with f235894e7e6b89d6c55d51dbfc6a4052792b1b9d

**Closed by marmotwb** 2015-08-27 20:25 UTC
Labels: bug, ready
