### ISSUE TITLE
Parse error: syntax error, unexpected '}' in wbstats help.php

### ISSUE THREAD

**Issue by qssocial** [WBCE/WebsiteBaker_CommunityEdition#91] opened 2016-01-07 02:11 UTC
Parse error: syntax error, unexpected '}' in D:\Programming\www\wamp22ap1\www\wbce12\modules\wbstats\help.php on line 34

Just delete line

**Comment by webbird** [comment] 2016-01-07 18:14
Fixed.
This was caused by commenting out a code block. Maybe we should remove that block, too.
Also fixed invalid `<br/>` to valid `<br />` (note the blank)

**Comment by qssocial** [comment] 2016-01-07 18:54
Thanks
When I have some time to check it and try to help.

**Closed** 2016-01-07 23:16 UTC
Labels: bug, ready
