### ISSUE TITLE
Topics 0.9.0RC - known issues

### ISSUE THREAD

**Issue by webbird** [WBCE/WebsiteBaker_CommunityEdition#3] opened 2015-07-06 10:34 UTC
After installation, there is a default topic explaining the module, but the access file is not created.

http://[domain]/pages/topics/welcome.php

**Comment by marmotwb** [comment] 2015-08-18 18:06
The Problem is at topics_archive_file () in functions_small.php at line 85 where $create_topics_accessfiles is not set.
So change the function signature to 
```function topics_archive_file ($filename, $t_id, $s_id, $p_id, $create_topics_accessfiles = 0) ```

And extend the call at line79 in add php to:
```topics_archive_file ($filename, $topic_id, $section_id, $page_id, $create_topics_accessfiles);```


Btw. there is an array to string error when deleting a topics page. This is caused in delete.php from line 60 where the wb system field $link is overwritten. So just rename the field for exeample like this:

	$topicLink = $query_details2->fetchRow();
	if(is_writable(WB_PATH.PAGES_DIRECTORY.$topicLink['link'].PAGE_EXTENSION)) {
		unlink(WB_PATH.PAGES_DIRECTORY.$topicLink['link'].PAGE_EXTENSION);

**Comment by marmotwb** [comment] 2015-08-21 17:56
Fixed with 02d872f12849577fe3370663117b7dd9afd8bdf8

**Closed by marmotwb** 2015-08-21 17:56 UTC
Labels: bug, ready
